// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehmgexpkhdeycthlhudz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobWdleHBraGRleWN0aGxodWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDUwMDUsImV4cCI6MjA2ODI4MTAwNX0.tOfjj1IPn4N_FNuJo-B9PDlvmL7MtjT5_IjIIurFMKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});